ServerEvents.tags('item', event => {
    event.add('concatenation:tech_cards', 'tarotcards:the_hierophant')
    event.add('concatenation:tech_cards', 'tarotcards:the_hermit')
    event.add('concatenation:magic_cards', 'tarotcards:temperance')
    event.add('concatenation:magic_cards', 'tarotcards:the_magician')
    event.add('concatenation:middle_cards', 'tarotcards:the_hermit')
    event.add('concatenation:middle_cards', 'tarotcards:the_magician')

    event.add('concatenation:hammers', 'concatenationcore:hammer')
    event.add('concatenation:hammers', 'concatenationcore:ironclad_hammer')

    event.add('forge:consumables/experience_3', 'concatenationcore:experience_orb')
    event.add('minecraft:swords', 'asr:diamond_giant_sword')
    event.add('minecraft:swords', 'asr:golden_giant_sword')
    event.add('minecraft:swords', 'asr:iron_giant_sword')
    event.add('minecraft:swords', 'asr:wooden_giant_sword')
    event.add('minecraft:swords', 'asr:stone_giant_sword')
    event.add('minecraft:swords', 'asr:ender_giant_sword')
    event.add('tarotcards:golden', 'asr:golden_giant_sword')
    event.add('tarotcards:golden', 'mekanismtools:gold_paxel')
    event.add('tarotcards:golden', 'farmersdelight:golden_knife')
    event.add('tarotcards:golden', 'dimdoors:rift_blade')
    event.add('tarotcards:golden', 'concatenationcore:shrike')
    event.add('tarotcards:golden', 'concatenationcore:kestrel')
    event.add('tarotcards:golden', 'concatenationcore:kestrel_r')
})