EmiPlusPlusEvents.registerGroups(event => {
    event.register("concatenation:facades", "ae2:facade")
    event.register("concatenation:botany_pots", "#botanypots:all_botany_pots")
    event.register("concatenation:syringes", "rftoolsutility:syringe")
    event.register("concatenation:ancient_knowledge", "spelled:ancient_knowledge_tome")

    event.register("concatenation:mekanism_fluid_ctanks", "mekanism:creative_fluid_tank")
    event.register("concatenation:mekanism_chemical_ctanks", "mekanism:creative_chemical_tank")

    event.register("concatenation:tconstruct_part_builders", "tconstruct:part_builder")
    event.register("concatenation:tconstruct_tinker_stations", "tconstruct:tinker_station")
    event.register("concatenation:tconstruct_tinkers_anvil", "tconstruct:tinkers_anvil")
    event.register("concatenation:tconstruct_scorched_anvil", "tconstruct:scorched_anvil")
    event.register("concatenation:leaf_pile", "#immersive_weathering:leaf_piles")
    event.register("concatenation:spikes", "supplementaries:bamboo_spikes_tipped")
    event.register("concatenation:bunting", "supplementaries:bunting")

    event.register("concatenation:tconstruct_seared_tanks", "tconstruct:seared_fuel_tank")
    event.register("concatenation:tconstruct_seared_tanks", "tconstruct:seared_ingot_fuel_tank")
    event.register("concatenation:tconstruct_scorched_tanks", "tconstruct:scorched_fuel_tank")
    event.register("concatenation:tconstruct_scorched_tanks", "tconstruct:scorched_ingot_fuel_tank")
    event.register("concatenation:scorched_fuel_gauge", "tconstruct:scorched_fuel_gauge")
    event.register("concatenation:scorched_fuel_gauge", "tconstruct:scorched_fuel_tank")
    event.register("concatenation:scorched_fuel_gauge", "tconstruct:scorched_ingot_gauge")
    event.register("concatenation:scorched_fuel_gauge", "tconstruct:scorched_ingot_tank")
    // event.register("concatenation:potion_bucket", "tconstruct:potion_bucket")

    // event.register("concatenation:repair_kit", "tconstruct:repair_kit")
    // event.register("concatenation:pick_head", "tconstruct:pick_head")
    // event.register("concatenation:small_axe_head", "tconstruct:small_axe_head")
    // event.register("concatenation:small_blade", "tconstruct:small_blade")
    // event.register("concatenation:adze_head", "tconstruct:adze_head")
    // event.register("concatenation:hammer_head", "tconstruct:hammer_head")
    // event.register("concatenation:broad_axe_head", "tconstruct:broad_axe_head")
    // event.register("concatenation:broad_blade", "tconstruct:broad_blade")
    // event.register("concatenation:large_plate", "tconstruct:large_plate")
    // event.register("concatenation:tool_handle", "tconstruct:tool_handle")
    // event.register("concatenation:tool_binding", "tconstruct:tool_binding")
    // event.register("concatenation:tough_handle", "tconstruct:tough_handle")
    // event.register("concatenation:tough_binding", "tconstruct:tough_binding")
    // event.register("concatenation:bow_limb", "tconstruct:bow_limb")
    // event.register("concatenation:bow_grip", "tconstruct:bow_grip")
    // event.register("concatenation:bowstring", "tconstruct:bowstring")
    // event.register("concatenation:arrow_head", "tconstruct:arrow_head")
    // event.register("concatenation:arrow_shaft", "tconstruct:arrow_shaft")
    // event.register("concatenation:fletching", "tconstruct:fletching")
    // event.register("concatenation:helmet_plating", "tconstruct:helmet_plating")
    // event.register("concatenation:chestplate_plating", "tconstruct:chestplate_plating")
    // event.register("concatenation:leggings_plating", "tconstruct:leggings_plating")
    // event.register("concatenation:boots_plating", "tconstruct:boots_plating")
    // event.register("concatenation:maille", "tconstruct:maille")
    // event.register("concatenation:shield_core", "tconstruct:shield_core")
    // event.register("concatenation:modifier_crystal", "tconstruct:modifier_crystal")
    // event.register("concatenation:crossbow", "tconstruct:crossbow")
    // event.register("concatenation:longbow", "tconstruct:longbow")
    // event.register("concatenation:fishing_rod", "tconstruct:fishing_rod")
    // event.register("concatenation:javelin", "tconstruct:javelin")
    // event.register("concatenation:arrow", "tconstruct:arrow")
    // event.register("concatenation:shuriken", "tconstruct:shuriken")
    // event.register("concatenation:throwing_axe", "tconstruct:throwing_axe")
    // event.register("concatenation:melting_pan", "tconstruct:melting_pan")
    // event.register("concatenation:battlesign", "tconstruct:battlesign")
    // event.register("concatenation:travelers_helmet", "tconstruct:travelers_helmet")
    // event.register("concatenation:travelers_chestplate", "tconstruct:travelers_chestplate")
    // event.register("concatenation:travelers_leggings", "tconstruct:travelers_leggings")
    // event.register("concatenation:travelers_boots", "tconstruct:travelers_boots")
    // event.register("concatenation:travelers_shield", "tconstruct:travelers_shield")
    // event.register("concatenation:plate_helmet", "tconstruct:plate_helmet")
    // event.register("concatenation:plate_chestplate", "tconstruct:plate_chestplate")
    // event.register("concatenation:plate_leggings", "tconstruct:plate_leggings")
    // event.register("concatenation:plate_boots", "tconstruct:plate_boots")
    // event.register("concatenation:plate_shield", "tconstruct:plate_shield")
    // event.register("concatenation:slender_blade", "tinker_rapier:slender_blade")

    event.register("concatenation:copper_can", "tconstruct:copper_can")
    event.register("concatenation:seared_fuel_gauge", "tconstruct:seared_fuel_gauge")
    event.register("concatenation:seared_lantern", "tconstruct:seared_lantern")
    event.register("concatenation:seared_ingot_gauge", "tconstruct:seared_ingot_gauge")
    event.register("concatenation:seared_ingot_tank", "tconstruct:seared_ingot_tank")
    event.register("concatenation:scorched_lantern", "tconstruct:scorched_lantern")

    event.register("concatenation:mob_charm_fragments", "reliquary:mob_charm_fragment")
    event.register("concatenation:mob_charms", "reliquary:mob_charm")
    // event.register("concatenation:potion_essence", "reliquary:potion_essence")
    // event.register("concatenation:tipped_arrow", "reliquary:tipped_arrow")
    // event.register("concatenation:potion", "reliquary:potion")
    // event.register("concatenation:splash_potion", "reliquary:splash_potion")
    // event.register("concatenation:lingering_potion", "reliquary:lingering_potion")
    // event.register("concatenation:magazines", "reliquary:magazines")
    // event.register("concatenation:bullets", "reliquary:bullets")
    // event.register("concatenation:pedestals", "reliquary:pedestals")

    // event.register("concatenation:upgradetome", "bloodmagic:upgradetome")
    // event.register("concatenation:scroll", "irons_spellbooks:scroll")
})