#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 03 22:43:51 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v3.3.zip
enableShaders=true
