#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< HEAD
#Thu Feb 05 23:06:25 EST 2026
=======
#Sun Feb 08 21:17:16 EST 2026
>>>>>>> parent of 689b005 (Revert "Merge branch 'main' into main")
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=Mellow Shader v1.5.5a.zip
enableShaders=true
